### ISSUE TITLE
Raft: heartbeat implementation

### ISSUE THREAD

**Issue by vitekkor** [vitekkor/mintKV#22]
С помощью AppendEntriesRequest лидер должен посылать heartbeats к своим фолловерам.
Если `entries` пуст, запрос интерпретируется как heartbeat

Необходимо реализовать логику периодической отправки таких сообщений всем фолловерам.

Класс RaftActor с ScheduledThreadPool. 

TODO:
* класс RaftActor
* реализовать в RaftActor метод sleepBeforeElections (или какое-то другое название) - отмена старой задачи (если она есть) и запуск новой фоновой отложенной задачи в ScheduledThreadPool. `delay = baseDelay (напр, 5000ms) + random.nextLong(1000, 5000);`. Задача сама пусть пока будет заглушкой и просто печать что-нибудь в консоль.
* реализовать в RaftActor метод onHeartBeat - при вызове метода должна писаться информация в логгер о вызове и метод должен вызывать sleepBeforeElections.
* При этом, если в RaftActor флаг `amILeader` равен true, то метод onHeartBeat должен выбрасывать исключение StatusException (из grpc, подключить библиотеку `implementation("io.grpc:grpc-services:${grpcVersion}")`) с кодом FAILED_PRECONDITION

**Comment by axothy** [comment]
как вычисляется amILeader?
