### ISSUE TITLE
onAppendEntryResult implementation

### ISSUE THREAD

**Issue by vitekkor** [vitekkor/mintKV#37]
### onAppendEntryResult

Функция onAppendEntryResult обрабатывает результаты выполнения команды AppendEntry от других узлов в распределенной системе. Рассмотрим её алгоритм по шагам:

### алгоритм

1. Чтение текущего состояния:
   - Функция начинает с чтения текущего состояния из хранилища (ReplicatedLogManager::readPersistentState).

2. Проверка term:
   - Если term в сообщении (message.term) меньше текущего term (state.currentTerm), функция завершает выполнение.
   - Если term в сообщении больше текущего term, узел становится последователем:
     - Идентификатор лидера (leaderId) сбрасывается.
     - Обновляется текущее состояние в хранилище с новым term (ReplicatedLogManager::writePersistentState).
     - Запускается таймаут для выборов (startTimeout Timeout.ELECTION_TIMEOUT).
     - Функция завершает выполнение.

3. Обработка результата:
   - Если message.lastIndex не равен -1, вызывается функция onSuccessfullAppendEntryResult для обработки успешного результата.
   - Если message.lastIndex равен -1, вызывается функция onFailedAppendEntryResult для обработки неудачного результата.

### onSuccessfullAppendEntryResult

1. Обновление индексов:
   - Обновляются nextIndex и matchIndex для узла srcId (nextIndex и matchIndex это массив int размера cluster.size()).

2. Проверка лидерства:
   - Проверяется, является ли текущий узел лидером (leaderId == nodeId).

3. Коммит записей:
   - Для каждого индекса от commitIndex (ReplicatedLogManager::commitIndex) + 1 до message.lastIndex:
     - Подсчитывается количество узлов, у которых matchIndex больше или равен текущему индексу N (`matchIndex.count { it >= N }` ).
     - Если количество узлов больше или равно quorum и term записи в логе для N равен текущему term (`count == quorum && ReplicatedLogManager.readLog(N)?.id?.term == state.currentTerm`):
       - Для каждого индекса от commitIndex + 1 до N:
          - Применяются команды из лога (StateMachine::apply)
          - Если нода лидер и если term logEntry равен текущему term, то добавляем CommandResult в список результатов
      - результаты отправляются клиентам (leaderResults.forEach(ExternalGrpcActorInterface::onClientCommandResult))
      - Обновляется индекс коммита (commitIndex).

### onFailedAppendEntryResult

1. Уменьшение nextIndex:
   - `nextIndex[srcId - 1] = nextIndex[srcId - 1] - 1;`

2. Проверка лидерства:
   - Если текущий узел не является лидером, функция завершает выполнение.

3. Отправка AppendEntriesRequest:
   - Читается запись в логе для lastIndex (`==nextIndex[srcId - 1]`).
   - Читается предыдущая запись в логе (`==nextIndex[srcId - 1] - 1`.
   - Формируется и отправляется RPC-запрос AppendEntriesRequest для узла srcId с целью синхронизации его лога с лидером.

**Comment by axothy** [comment]
В onSuccessfullAppendEntryResult наверное так `count => quorum && ReplicatedLogManager.readLog(N)?.id?.term == state.currentTerm`

(`count >= quorum`, вместо `count == quorum`)
